#!/bin/bash
if [ $1xxx == xxx ] || [ $2xxx == xxx ] || [ $3xxx == xxx ]
then
    echo "utilizzo: afronte <nome> <T1> <T2>"
else
    mkdir -p $1
    echo "costruzione link incrociati in $1 tra $2 e $3"
    sed -e "s/<b>\([0123456789]*\)<\/b><\/font>/<b><a href=\"$1-$3-1.htm#UN\1\" target=\"$3\">\1<\/a><\/b><\/font>/g" -e "s/target=\"variante\"/target=\"vv$2\"/g" $1-$2-1.htm > $1/$1-$2-1.htm
    sed -e "s/<b>\([0123456789]*\)<\/b><\/font>/<b><a href=\"$1-$2-1.htm#UN\1\" target=\"$2\">\1<\/a><\/b><\/font>/g" -e "s/target=\"variante\"/target=\"vv$3\"/g" $1-$3-1.htm > $1/$1-$3-1.htm
    sed -e "s/target=\"tc\"/target=\"$2\"/g" $1-$2-1v.htm > $1/$1-$2-1v.htm
    sed -e "s/target=\"tc\"/target=\"$3\"/g" $1-$3-1v.htm > $1/$1-$3-1v.htm
    echo "costruzione frameset per testi a fronte"
    echo "<frameset cols=\"50%,50%\">" > $1/$1-1f.htm
    echo "<frameset rows=\"70%,30%\">" >> $1/$1-1f.htm
    echo "<frame name=\"$2\" src=\"$1-$2-1.htm\">" >> $1/$1-1f.htm
    echo "<frame name=\"vv$2\" src=\"$1-$2-1v.htm\">" >> $1/$1-1f.htm
    echo "</frameset>" >> $1/$1-1f.htm
    echo "<frameset rows=\"70%,30%\">" >> $1/$1-1f.htm
    echo "<frame name=\"$3\" src=\"$1-$3-1.htm\">" >> $1/$1-1f.htm
    echo "<frame name=\"vv$3\" src=\"$1-$3-1v.htm\">" >> $1/$1-1f.htm
    echo "</frameset>" >> $1/$1-1f.htm
    echo "</frameset>" >> $1/$1-1f.htm
fi
